# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MK Photography
email: maggie9in@gmail.com
description: Passionate photographer for portrait, scenic, events, parties, birthdays, weddings, portfolio, candid and many more styles.
baseurl: "/snap-web"
url: "http://meghaphotography.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
