# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Megha Krishnamurthy Photography
email: meghavi.photography@gmail.com
description: Passionate photographer who specializes in portrait, candid, wedding and other event photography.
baseurl: ""
url: "http://meghaphotography.com" # the base hostname & protocol for your site
twitter_username:
github_username:
500px_username: "maggie9in"

# Build settings
markdown: kramdown
